# Generated by Django 6.0.7 on 2026-07-23 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='mobile_image',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
        migrations.AddField(
            model_name='banner',
            name='page',
            field=models.CharField(choices=[('home', 'Home'), ('shop', 'Shop'), ('sell', 'Sell Your Phone')], default='home', max_length=20),
        ),
    ]
