# Generated by Django 6.0.7 on 2026-07-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_banner_mobile_image_banner_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellyourphone',
            name='customer_address',
            field=models.TextField(blank=True),
        ),
    ]
