# Generated by Django 6.0.7 on 2026-07-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_aboutus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='page',
            field=models.CharField(choices=[('home', 'Home'), ('shop', 'Shop'), ('sell', 'Sell Your Phone'), ('about', 'About Us')], default='home', max_length=20),
        ),
    ]
