# Generated by Django 6.0.7 on 2026-07-31 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('warranty', 'Warranty Information'), ('returns', 'Returns & Refund Policy'), ('privacy', 'Privacy Policy'), ('terms', 'Terms & Conditions')], max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='banner',
            name='page',
            field=models.CharField(choices=[('home', 'Home'), ('shop', 'Shop'), ('sell', 'Sell Your Phone'), ('about', 'About Us'), ('contact', 'Contact Us'), ('faqs', 'FAQs')], default='home', max_length=20),
        ),
    ]
