# Generated by Django 6.0.7 on 2026-08-10 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_sectionbackground_mobile_background_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SectionBackground',
        ),
    ]
